---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitbot
  labels:
    app.kubernetes.io/name: gitbot
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitbot
