---
apiVersion: v1
kind: ServiceAccount
# automountServiceAccountToken: false
metadata:
  name: gitbot
  labels:
    app.kubernetes.io/name: gitbot

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitbot
  labels:
    app.kubernetes.io/name: gitbot
rules:
  - apiGroups: ["argoproj.io"]
    verbs: ["get", "list", "watch", "patch", "update"]
    resources:
    - applications
    - applicationsets
    - applicationsets/finalizers
    - applicationsets/status

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitbot
subjects:
  - kind: ServiceAccount
    name: gitbot
    namespace: argocd
