---
apiVersion: v1
kind: Service
metadata:
  name: gitbot
  labels:
    app.kubernetes.io/name: gitbot
spec:
  selector:
    app.kubernetes.io/name: gitbot
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
