---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - gitbot-service.yaml
  - gitbot-rbac.yaml
  - gitbot-deployment.yaml
  - gitbot-pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: gitbot
      app.kubernetes.io/instance: gitbot
    includeSelectors: true

